name: Docker Publish Workflow

on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      cassandra:
        image: cassandra:latest
        ports:
          - 9043:9042
        options: --name cassandra-chatmedia
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Wait for Cassandra to start
        run: sleep 60 # Wait for 1 minute before creating the keyspace

      - name: Initialize Cassandra schema
        run: |
          echo "CREATE KEYSPACE IF NOT EXISTS chatmedia_keyspace WITH REPLICATION = {'class' : 'SimpleStrategy', 'replication_factor' : 1};" > schema.cql
          echo "CREATE TABLE IF NOT EXISTS media_metadata (id UUID PRIMARY KEY, media_type TEXT, size BIGINT, url TEXT);" >> schema.cql
          docker run --rm --network container:cassandra -v ${PWD}:/workspace -w /workspace --entrypoint=cqlsh cassandra-chatmedia -f schema.cql
      - name: Build and test
        env:
          SPRING_DATASOURCE_URL: "jdbc:cassandra://localhost:9043/media_metadata"
        run: mvn -B clean verify
      
      - name: Set up Docker Buildx
        if: ${{ success() }} # Add this line
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        if: ${{ success() }} # Add this line
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        if: ${{ success() }}
        uses: docker/build-push-action@v2
        with:
          context: sevyhchatmediaservice
          push: true
          tags: jjuless/sevyhchatmediaservice:latest
